import morgan from "morgan";
import { Request, Response } from "express";

// Attach the request ID generated by errorHandler into morgan's output
morgan.token("req-id", (req: Request) => req.headers["x-request-id"] as string ?? "-");

// Combined-style log with request ID prefix so every line is traceable
const requestLogger = morgan(
    ':req-id :method :url :status :res[content-length] bytes - :response-time ms'
);

export default requestLogger;
